apiVersion: v1
kind: Pod
metadata: 
 name: labels
 labels: 
  enviroment: production
  app: nginx
spec:
  containers:
    - name: nginx-labels
      image: nginx
      ports:  
      - containerPort: 80
