apiVersion: v1
kind: Pod   
metadata: 
  name: resource
spec:
  containers:
   - name: nginx
     image: nginx
     resource: 
      requests: 
       cpu: "100m"
       memory: "128Mi"
      limits:
       cpu: "200m"
       memory: "256Mi"       
