apiVersion: v1 
kind: Pod  
metadata: 
 name: mypodconfig
spec: 
 containers:
 - name: mypodconfig
   image: nginx
   env: 
   - name: Course
     valueFrom:
      configMapKeyRef:
        name: myconfigmap
        key: Course
   - name: Duration
     valueFrom:
       configMapKeyRef:
         name: myconfigmap
         key: Duration
   - name: TRAINER 
     valueFrom: 
       configMapKeyRef:
         name: myconfigmap
         key: TRAINER