apiVersion: v1  
kind: Secret  
metadata: 
  name: secret-basic-auth
data:
 password: UyFCXCpkJHpEc2I9
 username: YWRtaW4=
---
apiVersion: v1
kind: Pod 
metadata: 
  name: secret-pod
spec: 
  containers:
    - name: config-pod-direct
      image: nginx
      envFrom:
      - secretRef:
          name: secret-basic-auth   

