apiVersion: v1
kind: Pod 
meatadata: 
 name: nginx
 labels: 
   environment: develop
   app: frontend 
spec: 
 containers:
   - name: nginx
     image: nginx
     ports: 
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1 
kind: Service
metadata:
  name:  nginx-service
spec:
  selector:
    environment: develop
    app : frontend
  ports:
  - name:  name-of-service-port
    protocol: TCP
    port: 80
    targetPort:  http-web-svc

